# Generated by Django 6.0 on 2025-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=6)),
                ('stock_name', models.TextField()),
                ('recent_price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
