# Generated by Django 6.0 on 2025-12-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_ticker',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
