# Generated by Django 6.0 on 2026-01-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_alter_stock_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='listed_index',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
