# Generated by Django 6.0 on 2026-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_stock_listed_index_stock_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='consolidated',
            field=models.BooleanField(default=True),
        ),
    ]
